"""restore the indexes dropped by 73fd123a60aa

Revision ID: 4d0e9b1a8c6f
Revises: 8a6766f6326b
Create Date: 2026-10-09 11:00:00.000000

The autogenerated ``73fd123a60aa_redeploy`` dropped three indexes that the
models did not declare (.github#7 K):

- ``uq_tasks_active_per_deployment``: at most one PENDING/RUNNING task per
  deployment, the database backstop of the dispatch flow
  (``task_service.prepare_task_in_tx``);
- ``ix_apps_live`` and ``ix_deployments_live``: the default queries that
  hide soft-deleted rows.

The models declare them now, so ``alembic check`` keeps them. Older active
duplicates are failed first (keeping the newest per deployment), or the
unique index could not be built; they cannot be running for real, the
dispatch flow never let a second one through.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d0e9b1a8c6f"
down_revision: Union[str, None] = "8a6766f6326b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        UPDATE tasks t
           SET status = 'FAILED',
               finished_at = timezone('UTC', now()),
               logs = COALESCE(t.logs || E'\\n\\n', '')
                      || 'Migration 4d0e9b1a8c6f: superseded by a newer active task of the same deployment'
         WHERE t.status IN ('PENDING', 'RUNNING')
           AND EXISTS (
                SELECT 1 FROM tasks n
                 WHERE n."deploymentId" = t."deploymentId"
                   AND n.status IN ('PENDING', 'RUNNING')
                   AND (n.created_at, n."taskId") > (t.created_at, t."taskId"))
        """
    )
    op.create_index(
        "uq_tasks_active_per_deployment",
        "tasks",
        ["deploymentId"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"),
    )
    op.create_index("ix_apps_live", "apps", ["appId"], postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index(
        "ix_deployments_live", "deployments", ["deploymentId"], postgresql_where=sa.text("deleted_at IS NULL")
    )


def downgrade() -> None:
    op.drop_index("ix_deployments_live", table_name="deployments")
    op.drop_index("ix_apps_live", table_name="apps")
    op.drop_index("uq_tasks_active_per_deployment", table_name="tasks")
